dictionaries:
  - en
  - en_GB

excluded_files:
  - ".typo-ci.yml"
  - "*.css"
  - "*.js"
  - "assets/img/**"
  - "showcase/index.php"

excluded_words:
  - centos
  - company-gfx
  - idvservices
  - rizzuto
  - typoci
  - uikit
